### ISSUE TITLE
package installation

### ISSUE THREAD

**Issue by Elennahan** [elakkis/SDID#1]
Firstly, thanks for your providing such a wonderful package.

But when I tried to install your package in R studio, it told me it not include in R 3.5.3, so I am requesting some possible advice frome you.

**Comment by elakkis** [comment]
Thank you for your feedback!

Could you let me know the R version you are using?

**Comment by Elennahan** [comment]
I am using the R version 3.5.3.

**Comment by elakkis** [comment]
To install the package:

library(devtools)
install_github("elakkis/SDID")

**Comment by Elennahan** [comment]
thanks very much, given your feedback, the problem has been solved
